#!/usr/bin/env python

import os

for var_name in [
        'CI', 'CIRCLECI', 'CIRCLE_BRANCH', 'CIRCLE_BUILD_NUM', 'CIRCLE_BUILD_URL', 'CIRCLE_JOB',
        'CIRCLE_NODE_INDEX', 'CIRCLE_NODE_TOTAL', 'CIRCLE_PR_NUMBER', 'CIRCLE_PR_REPONAME', 'CIRCLE_PR_USERNAME',
        'CIRCLE_PREVIOUS_BUILD_NUM', 'CIRCLE_PROJECT_REPONAME', 'CIRCLE_PROJECT_USERNAME', 'CIRCLE_PULL_REQUEST',
        'CIRCLE_PULL_REQUESTS', 'CIRCLE_REPOSITORY_URL', 'CIRCLE_SHA1', 'CIRCLE_TAG', 'CIRCLE_USERNAME', 'CIRCLE_WORKFLOW_ID',
        'CIRCLE_WORKING_DIRECTORY', 'CIRCLE_INTERNAL_TASK_DATA', 'CIRCLE_COMPARE_URL', 'CI_PULL_REQUEST', 'CI_PULL_REQUESTS']:
    print(var_name, os.environ.get(var_name, None))
